feat: написать пилотную версию проекта в ветке controllers-films-users
SergeiBrin/java-filmorate pull request #1
Opened 2023-01-09 10:02 UTC by SergeiBrin

2023-01-09 11:30 UTC, SergeiBrin commented
Привет, Эркин 😀. С наступившим тебя Новым годом. Пусть в этом году сбудутся все твои мечты 🥳😇

2023-01-10 11:23 UTC, ErkinKasymaliev requested changes
Привет, Сергей!
Тебя также с Наступившим!
Я оставил комменты UserController, они также аналогичны и для FilmController

2023-01-10 11:23 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +@RequestMapping("/films")
здесь правильно что сразу url указал

2023-01-10 11:23 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +                    exceptionMessage.add("Пользователя с таким id нет");
это не валидация. Валидация - это когда проверяешь входные данные, а не полученные с твоего хранилища

2023-01-10 11:23 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private void validateUser(User user, String methodName) {
этот метод можно сделать намного короче через аннотации в моделька, про которые написано в разделе со *, так что не ленись и попробуй сделать через аннотации. Если постараться, то метод validate можете даже не понадобиться.

2023-01-19 17:50 UTC, ErkinKasymaliev approved these changes
Работа принята

2023-01-19 17:59 UTC, merged