ТЗ 10: Add friends likes
SergeiBrin/java-filmorate pull request #2
Opened 2023-02-04 23:43 UTC by SergeiBrin

2023-02-04 23:46 UTC, SergeiBrin commented
Привет Эркин :)

2023-02-05 11:17 UTC, ErkinKasymaliev requested changes
привет, Сергей!
оставил комменты

2023-02-05 11:17 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
> +    private final FilmService filmService;
сюда надо инжектить только сервисы, то есть вот ты написал "return filmStorage.getAllFilms();" - это у тебя должно быть в FilmService в методе например getAllFilms();
вместо UserStorage надо инжектить userService.

2023-02-05 11:17 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/user/UserController.java
> +    private final UserStorage userStorage;
в контроллере надо инжектить только сервисы

2023-02-05 11:17 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/user/UserController.java
> +        if (userId == null) {
давай валидации уберем в отдельный метод или класс

2023-02-06 13:56 UTC, SergeiBrin commented
Привет, Эркин. Это снова я))))

Итак, storage из контроллеров убрал, перенаправил работу через service.
Для валидации и проброса ошибок на входящие id сделал отдельный класс Validator.

Воть :)))

2023-02-07 08:36 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.
на будущее когда у тебя будет много коммитов после ревью - то сперва сделай squash чтобы собрать их все в один и пуш. Так удобнее проверять.

2023-02-07 08:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    public UserService(InMemoryUserStorage userStorage) { // Может быть тут нужен UserStorage?
да именно так

2023-02-07 08:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage) {
сюда инжекти FilmStorage

2023-02-07 08:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/validation/validator/Validator.java
> +@Data
этого не надо

2023-02-07 12:55 UTC, SergeiBrin commented
Привет Эркин. В этот раз я не сделал squash - прости). К следующему разу я разберусь и обязательно его сделаю :)

2023-02-07 13:45 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +@Getter
отсюда и из InMemoryUserStorage убери сеттеры и геттеры

2023-02-07 13:47 UTC, ErkinKasymaliev approved these changes
Работа принята!
Оставил 1 коммент - поправь его к следующей работе.
Насчет squash - загугли intellij squash commits.

2023-02-15 05:33 UTC, merged