Add database H2 and logic to work with it
SergeiBrin/java-filmorate pull request #3
Opened 2023-03-19 01:11 UTC by SergeiBrin

2023-03-19 02:55 UTC, SergeiBrin commented
Привет, Эркин. Как дела?))) Божечки, я наконец-то довел это ТЗ 11 до рабочего состояния, - и я так рад)))). В этот раз конечно было нелегко. Ух. Даже чуточку поплохело однажды от того, что слишком много думал. Но, всё равно, я всё прошёл, всё победил. Я очень постарался, Эркин, в принципе, как и всегда, поэтому скрещиваю пальчики, чтобы правок  на твой взгляд оказалось немного - ибо в среду дедлайн :(. Боюсь, боюсь, боюсь... В этот раз под первую итерацию склеил все одним коммитом типа «first commit add database,,,», и уже отправляю тебе ссылку на проверку. Ну и до скорых встреч 😃

2023-03-19 17:24 UTC, ErkinKasymaliev requested changes
привет, у меня все хорошо, как сам?
Оставил комменты, думаю к пн ты их успеешь поправить.

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
> -@RequestMapping("/films")
лучше оставь как было

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
>          validator.checkFilmByPathVariableId(filmId);
проверять на валидацию PathVariable не надо, так он часть url, если его не укажут, то контроллер просто не вызовется

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
>          return filmService.postFilm(film);
лучше createFilm

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
>          return filmService.putFilm(film);
лучше updateFilm

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/user/UserController.java
>  public class UserController {
аналогичные комменты в FilmController

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/GenreNotFoundException.java
> +public class GenreNotFoundException extends RuntimeException {
создай лучше один Exception EntityNotFoundException

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean addGenre(Set<Genre> genre) {
ммм...
попробуй так:
public void addGenre(Genre genre) {
   if(genres == null) { genres = new HashSet()}
 		genres.add(genre);
 }

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      public boolean addLike(Long userId) {
смотри выше

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Map<Long, Boolean> friends = new HashMap<>();
это тебе не надо, у тебя уже есть Friendship

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
почему этот класс у тебя здесь? у тебя уже есть пакет Dao, перенеси со storage все туда и приведи в единый вид с названием

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/PopularFilmsDaoImpl.java
> +public class PopularFilmsDaoImpl implements PopularFilmsDao {
не надо создавать отдельную таблицу для популярных фильм. Популярные фильмы ты должен достать из запроса из таблицы film с учетом таблицы likes

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/validation/validator/RAMValidator.java
> +public class RAMValidator implements Validator {
RAM неудачное название, лучше InMemory

2023-03-19 17:24 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
> +    private final FilmDbService filmService;
так не пойдет, внедрение зависимости не должно зависеть от реализации. верни FilmService. Так как у тебя в FilmDbService стоит аннотация @Primary, то это реализации итак будет использоваться

2023-03-19 20:56 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
> +    private final FilmDbService filmService;
+

2023-03-19 21:00 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/validation/validator/RAMValidator.java
> +public class RAMValidator implements Validator {
🆗

2023-03-19 21:46 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/PopularFilmsDaoImpl.java
> +public class PopularFilmsDaoImpl implements PopularFilmsDao {
🆗

2023-03-19 21:57 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
🆗

2023-03-19 22:05 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Map<Long, Boolean> friends = new HashMap<>();
❓ Я использую этот Map, чтобы возвращать клиенту объект User с информацией о дружбе. А ещe этот Map связан с логикой InMemoryStorage. И если Map удалить, то придется тогда еще удалять часть кода в InMemoryStorage. Эркин, как быть?

2023-03-19 22:23 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/GenreNotFoundException.java
> +public class GenreNotFoundException extends RuntimeException {
✅

2023-03-19 23:23 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
> -@RequestMapping("/films")
❓ Если оставить, как было, то не будут работать пути для mpa и genre, потому что в их url нет "/films". Как быть?

2023-03-19 23:34 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
>          return filmService.postFilm(film);
✅

2023-03-19 23:34 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
>          return filmService.putFilm(film);
✅

2023-03-19 23:34 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/user/UserController.java
>  public class UserController {
✅

2023-03-19 23:59 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean addGenre(Set<Genre> genre) {
🇶🇦 
Попробовал, не работает. Та же самая ошибка. Оставляю тогда как рекомендуют на сайте baeldung. Да?

2023-03-19 23:59 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      public boolean addLike(Long userId) {
🇶🇦
Попробовал, не работает. Та же самая ошибка. Оставляю тогда как рекомендуют на сайте baeldung. Да?

2023-03-20 00:30 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
>          validator.checkFilmByPathVariableId(filmId);
✅ Изменил названия и логику проверки. Теперь для PathVariable в Validator я проверяю только наличие объекта в базе по id. И если объекта нет, то выбрасываю EntityNotFoundException()

2023-03-20 01:38 UTC, SergeiBrin commented
Эркин. Это снова я. Привет))). Я очень рад, что у тебя дела хорошо 😄. У меня дела непонятно, но бывало и хуже :)

Я замечания проработал. Однако по паре замечаний я оставил тебе комменты - со знаками ❓ и  🇶🇦. Там есть некоторые нюансы, поэтому они остались нетронутыми.

А ещё я сделал Squash, как ты меня и просил, чтобы тебе было удобней проверять. Вот 😎

2023-03-20 08:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
> -@RequestMapping("/films")
создай отдельные контроллеры для mpa и genre

2023-03-20 08:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
>          validator.checkFilmByPathVariableId(filmId);
это правильно

2023-03-20 08:59 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Map<Long, Boolean> friends = new HashMap<>();
возвращаю клиенту друзей через запрос

2023-03-20 09:18 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-03-20 09:18 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean addGenre(Set<Genre> genre) {
нет, так как каждый раз когда будешь добавлять жанр у тебя будет создаваться новый сет с 1 жанром, а жанров может быть несколько

2023-03-20 09:18 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean addGenre(Set<Genre> genre) {
я чет не нашел где ты его используешь, в принципе можешь и удалить

2023-03-21 01:38 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Map<Long, Boolean> friends = new HashMap<>();
✅

2023-03-21 01:38 UTC, SergeiBrin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/film/FilmController.java
> -@RequestMapping("/films")
✅

2023-03-21 01:47 UTC, SergeiBrin commented
Пара пара пам))))

2023-03-21 08:56 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-27 17:01 UTC, merged